In [17]:
import pandas as pd

df = pd.read_csv(
    "../dataset/final_dataset.csv"
)

df = df[["title", "label"]]

df.head()

                                               title  label
0  Did Miley Cyrus and Liam Hemsworth secretly ge...      0
1  Paris Jackson & Cara Delevingne Enjoy Night Ou...      0
2  Celebrities Join Tax March in Protest of Donal...      0
3  Cindy Crawford's daughter Kaia Gerber wears a ...      0
4      Full List of 2018 Oscar Nominations – Variety      0

In [18]:
from sklearn.model_selection import train_test_split

train_texts, test_texts, train_labels, test_labels = train_test_split(
    df["title"],
    df["label"],
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

In [19]:
from transformers import DistilBertTokenizer

tokenizer = DistilBertTokenizer.from_pretrained(
    "distilbert-base-uncased"
)

In [20]:
train_encodings = tokenizer(
    list(train_texts),
    truncation=True,
    padding=True,
    max_length=64
)

test_encodings = tokenizer(
    list(test_texts),
    truncation=True,
    padding=True,
    max_length=64
)

In [21]:
import torch

class NewsDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = list(labels)

    def __getitem__(self, idx):

        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }

        item["labels"] = torch.tensor(
            self.labels[idx]
        )

        return item

    def __len__(self):
        return len(self.labels)

In [22]:
train_dataset = NewsDataset(
    train_encodings,
    train_labels
)

test_dataset = NewsDataset(
    test_encodings,
    test_labels
)

In [23]:
from transformers import DistilBertForSequenceClassification

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [24]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",

    num_train_epochs=3,

    per_device_train_batch_size=4,

    per_device_eval_batch_size=4,

    eval_strategy="epoch",

    save_strategy="epoch",

    logging_steps=100,

    load_best_model_at_end=True
)

In [25]:
import numpy as np
from transformers import Trainer
from sklearn.metrics import accuracy_score

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(
        logits,
        axis=1
    )

    acc = accuracy_score(
        labels,
        predictions
    )

    return {
        "accuracy": acc
    }
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

In [26]:
trainer.train()

C:\Users\HP\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\HP\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\HP\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

TrainOutput(global_step=13917, training_loss=0.38724707950675097, metrics={'train_runtime': 10445.9406, 'train_samples_per_second': 5.329, 'train_steps_per_second': 1.332, 'total_flos': 921774393547776.0, 'train_loss': 0.38724707950675097, 'epoch': 3.0})

In [31]:
trainer.state

TrainerState(epoch=3.0, global_step=13917, max_steps=13917, logging_steps=100, eval_steps=500, save_steps=500, train_batch_size=4, num_train_epochs=3, num_input_tokens_seen=0, total_flos=921774393547776.0, log_history=[{'loss': 0.649427261352539, 'grad_norm': 2.456874370574951, 'learning_rate': 4.9644319896529426e-05, 'epoch': 0.02155636990730761, 'step': 100}, {'loss': 0.5689318466186524, 'grad_norm': 4.178120136260986, 'learning_rate': 4.9285047064740966e-05, 'epoch': 0.04311273981461522, 'step': 200}, {'loss': 0.5436323547363281, 'grad_norm': 6.797926902770996, 'learning_rate': 4.8925774232952506e-05, 'epoch': 0.06466910972192283, 'step': 300}, {'loss': 0.550029411315918, 'grad_norm': 5.030547142028809, 'learning_rate': 4.8566501401164046e-05, 'epoch': 0.08622547962923044, 'step': 400}, {'loss': 0.5488957977294922, 'grad_norm': 13.459747314453125, 'learning_rate': 4.8207228569375586e-05, 'epoch': 0.10778184953653805, 'step': 500}, {'loss': 0.5470691299438477, 'grad_norm': 10.633590698242188, 'learning_rate': 4.7847955737587126e-05, 'epoch': 0.12933821944384566, 'step': 600}, {'loss': 0.5051400375366211, 'grad_norm': 1.6329576969146729, 'learning_rate': 4.7488682905798666e-05, 'epoch': 0.15089458935115327, 'step': 700}, {'loss': 0.5577233505249023, 'grad_norm': 0.3657122254371643, 'learning_rate': 4.7129410074010206e-05, 'epoch': 0.17245095925846088, 'step': 800}, {'loss': 0.5485895538330078, 'grad_norm': 3.3412210941314697, 'learning_rate': 4.6770137242221745e-05, 'epoch': 0.1940073291657685, 'step': 900}, {'loss': 0.5176635360717774, 'grad_norm': 8.557476043701172, 'learning_rate': 4.6410864410433285e-05, 'epoch': 0.2155636990730761, 'step': 1000}, {'loss': 0.48968944549560545, 'grad_norm': 10.193718910217285, 'learning_rate': 4.6051591578644825e-05, 'epoch': 0.2371200689803837, 'step': 1100}, {'loss': 0.5690785217285156, 'grad_norm': 6.947571277618408, 'learning_rate': 4.5692318746856365e-05, 'epoch': 0.2586764388876913, 'step': 1200}, {'loss': 0.4793501281738281, 'grad_norm': 13.725885391235352, 'learning_rate': 4.5333045915067905e-05, 'epoch': 0.2802328087949989, 'step': 1300}, {'loss': 0.5091002273559571, 'grad_norm': 1.3259477615356445, 'learning_rate': 4.4973773083279445e-05, 'epoch': 0.30178917870230654, 'step': 1400}, {'loss': 0.5661604690551758, 'grad_norm': 4.261037826538086, 'learning_rate': 4.4614500251490985e-05, 'epoch': 0.3233455486096141, 'step': 1500}, {'loss': 0.5163994216918946, 'grad_norm': 7.716232776641846, 'learning_rate': 4.4255227419702525e-05, 'epoch': 0.34490191851692176, 'step': 1600}, {'loss': 0.5029531860351563, 'grad_norm': 0.7001529335975647, 'learning_rate': 4.3895954587914065e-05, 'epoch': 0.36645828842422934, 'step': 1700}, {'loss': 0.4885578155517578, 'grad_norm': 5.885401725769043, 'learning_rate': 4.3536681756125605e-05, 'epoch': 0.388014658331537, 'step': 1800}, {'loss': 0.5883298873901367, 'grad_norm': 9.875408172607422, 'learning_rate': 4.3177408924337144e-05, 'epoch': 0.40957102823884456, 'step': 1900}, {'loss': 0.5544414520263672, 'grad_norm': 3.1513168811798096, 'learning_rate': 4.2818136092548684e-05, 'epoch': 0.4311273981461522, 'step': 2000}, {'loss': 0.4911672592163086, 'grad_norm': 0.7372574210166931, 'learning_rate': 4.2458863260760224e-05, 'epoch': 0.4526837680534598, 'step': 2100}, {'loss': 0.5086845779418945, 'grad_norm': 4.209530353546143, 'learning_rate': 4.2099590428971764e-05, 'epoch': 0.4742401379607674, 'step': 2200}, {'loss': 0.508800048828125, 'grad_norm': 0.5632041096687317, 'learning_rate': 4.1740317597183304e-05, 'epoch': 0.495796507868075, 'step': 2300}, {'loss': 0.4767219924926758, 'grad_norm': 0.33107686042785645, 'learning_rate': 4.1381044765394844e-05, 'epoch': 0.5173528777753826, 'step': 2400}, {'loss': 0.47765407562255857, 'grad_norm': 0.2333901822566986, 'learning_rate': 4.1021771933606384e-05, 'epoch': 0.5389092476826902, 'step': 2500}, {'loss': 0.47352760314941406, 'grad_norm': 0.25099971890449524, 'learning_rate': 4.0662499101817924e-05, 'epoch': 0.5604656175899978, 'step': 2600}, {'loss': 0.4777238845825195, 'grad_norm': 11.69591999053955, 'learning_rate': 4.0303226270029464e-05, 'epoch': 0.5820219874973055, 'step': 2700}, {'loss': 0.4876824188232422, 'grad_norm': 14.030555725097656, 'learning_rate': 3.9943953438241e-05, 'epoch': 0.6035783574046131, 'step': 2800}, {'loss': 0.4916866683959961, 'grad_norm': 18.071565628051758, 'learning_rate': 3.958468060645254e-05, 'epoch': 0.6251347273119207, 'step': 2900}, {'loss': 0.5187668228149414, 'grad_norm': 28.050006866455078, 'learning_rate': 3.922540777466408e-05, 'epoch': 0.6466910972192282, 'step': 3000}, {'loss': 0.48537273406982423, 'grad_norm': 4.64512300491333, 'learning_rate': 3.886613494287562e-05, 'epoch': 0.6682474671265359, 'step': 3100}, {'loss': 0.4360238647460937, 'grad_norm': 0.5189858675003052, 'learning_rate': 3.850686211108716e-05, 'epoch': 0.6898038370338435, 'step': 3200}, {'loss': 0.5123825073242188, 'grad_norm': 47.61983108520508, 'learning_rate': 3.81475892792987e-05, 'epoch': 0.7113602069411511, 'step': 3300}, {'loss': 0.49509735107421876, 'grad_norm': 3.534775733947754, 'learning_rate': 3.778831644751024e-05, 'epoch': 0.7329165768484587, 'step': 3400}, {'loss': 0.49427898406982423, 'grad_norm': 6.253656387329102, 'learning_rate': 3.742904361572178e-05, 'epoch': 0.7544729467557664, 'step': 3500}, {'loss': 0.5096316528320313, 'grad_norm': 12.58210277557373, 'learning_rate': 3.706977078393332e-05, 'epoch': 0.776029316663074, 'step': 3600}, {'loss': 0.5307620620727539, 'grad_norm': 0.7574653029441833, 'learning_rate': 3.671049795214486e-05, 'epoch': 0.7975856865703815, 'step': 3700}, {'loss': 0.4937924957275391, 'grad_norm': 2.548395872116089, 'learning_rate': 3.63512251203564e-05, 'epoch': 0.8191420564776891, 'step': 3800}, {'loss': 0.36915355682373047, 'grad_norm': 21.14425277709961, 'learning_rate': 3.599195228856794e-05, 'epoch': 0.8406984263849968, 'step': 3900}, {'loss': 0.44329940795898437, 'grad_norm': 18.264890670776367, 'learning_rate': 3.5632679456779476e-05, 'epoch': 0.8622547962923044, 'step': 4000}, {'loss': 0.5043369674682617, 'grad_norm': 1.1149948835372925, 'learning_rate': 3.5273406624991015e-05, 'epoch': 0.883811166199612, 'step': 4100}, {'loss': 0.3673215866088867, 'grad_norm': 1.527889370918274, 'learning_rate': 3.4914133793202555e-05, 'epoch': 0.9053675361069196, 'step': 4200}, {'loss': 0.5705500411987304, 'grad_norm': 31.64800453186035, 'learning_rate': 3.4554860961414095e-05, 'epoch': 0.9269239060142273, 'step': 4300}, {'loss': 0.46319141387939455, 'grad_norm': 14.008389472961426, 'learning_rate': 3.419558812962564e-05, 'epoch': 0.9484802759215348, 'step': 4400}, {'loss': 0.4830466079711914, 'grad_norm': 13.132074356079102, 'learning_rate': 3.383631529783718e-05, 'epoch': 0.9700366458288424, 'step': 4500}, {'loss': 0.4332601165771484, 'grad_norm': 11.021404266357422, 'learning_rate': 3.347704246604872e-05, 'epoch': 0.99159301573615, 'step': 4600}, {'eval_loss': 0.45451411604881287, 'eval_accuracy': 0.8515086206896552, 'eval_runtime': 178.0236, 'eval_samples_per_second': 26.064, 'eval_steps_per_second': 6.516, 'epoch': 1.0, 'step': 4639}, {'loss': 0.47998268127441407, 'grad_norm': 0.581695020198822, 'learning_rate': 3.311776963426026e-05, 'epoch': 1.0131493856434577, 'step': 4700}, {'loss': 0.4225130462646484, 'grad_norm': 56.29866027832031, 'learning_rate': 3.27584968024718e-05, 'epoch': 1.0347057555507653, 'step': 4800}, {'loss': 0.3887526321411133, 'grad_norm': 9.541277885437012, 'learning_rate': 3.239922397068334e-05, 'epoch': 1.0562621254580729, 'step': 4900}, {'loss': 0.3555747985839844, 'grad_norm': 0.15502674877643585, 'learning_rate': 3.203995113889488e-05, 'epoch': 1.0778184953653804, 'step': 5000}, {'loss': 0.3891304016113281, 'grad_norm': 42.82186508178711, 'learning_rate': 3.168067830710642e-05, 'epoch': 1.099374865272688, 'step': 5100}, {'loss': 0.4064744186401367, 'grad_norm': 9.394201278686523, 'learning_rate': 3.1321405475317954e-05, 'epoch': 1.1209312351799956, 'step': 5200}, {'loss': 0.38579349517822265, 'grad_norm': 6.138237476348877, 'learning_rate': 3.0962132643529494e-05, 'epoch': 1.1424876050873034, 'step': 5300}, {'loss': 0.38409297943115234, 'grad_norm': 2.5693464279174805, 'learning_rate': 3.0602859811741034e-05, 'epoch': 1.164043974994611, 'step': 5400}, {'loss': 0.37899559020996093, 'grad_norm': 14.053366661071777, 'learning_rate': 3.0243586979952577e-05, 'epoch': 1.1856003449019186, 'step': 5500}, {'loss': 0.3760108947753906, 'grad_norm': 0.2080354541540146, 'learning_rate': 2.9884314148164117e-05, 'epoch': 1.2071567148092262, 'step': 5600}, {'loss': 0.38313827514648435, 'grad_norm': 0.5878360271453857, 'learning_rate': 2.9525041316375657e-05, 'epoch': 1.2287130847165337, 'step': 5700}, {'loss': 0.39642440795898437, 'grad_norm': 7.586039066314697, 'learning_rate': 2.9165768484587197e-05, 'epoch': 1.2502694546238413, 'step': 5800}, {'loss': 0.36424949645996096, 'grad_norm': 60.328582763671875, 'learning_rate': 2.8806495652798737e-05, 'epoch': 1.271825824531149, 'step': 5900}, {'loss': 0.45738399505615235, 'grad_norm': 0.2918982207775116, 'learning_rate': 2.8447222821010277e-05, 'epoch': 1.2933821944384567, 'step': 6000}, {'loss': 0.36551891326904296, 'grad_norm': 0.1869691014289856, 'learning_rate': 2.8087949989221817e-05, 'epoch': 1.314938564345764, 'step': 6100}, {'loss': 0.413582878112793, 'grad_norm': 0.5408746600151062, 'learning_rate': 2.7728677157433357e-05, 'epoch': 1.3364949342530719, 'step': 6200}, {'loss': 0.34023269653320315, 'grad_norm': 0.20026253163814545, 'learning_rate': 2.73694043256449e-05, 'epoch': 1.3580513041603794, 'step': 6300}, {'loss': 0.33970935821533205, 'grad_norm': 0.146327406167984, 'learning_rate': 2.7010131493856433e-05, 'epoch': 1.379607674067687, 'step': 6400}, {'loss': 0.37701759338378904, 'grad_norm': 10.177059173583984, 'learning_rate': 2.6650858662067973e-05, 'epoch': 1.4011640439749946, 'step': 6500}, {'loss': 0.39024967193603516, 'grad_norm': 0.9606387615203857, 'learning_rate': 2.6291585830279513e-05, 'epoch': 1.4227204138823022, 'step': 6600}, {'loss': 0.3709599685668945, 'grad_norm': 0.21829499304294586, 'learning_rate': 2.5932312998491053e-05, 'epoch': 1.4442767837896098, 'step': 6700}, {'loss': 0.3480175018310547, 'grad_norm': 21.234508514404297, 'learning_rate': 2.5573040166702593e-05, 'epoch': 1.4658331536969174, 'step': 6800}, {'loss': 0.4914150619506836, 'grad_norm': 0.2491675764322281, 'learning_rate': 2.5213767334914136e-05, 'epoch': 1.4873895236042252, 'step': 6900}, {'loss': 0.40262622833251954, 'grad_norm': 74.7975845336914, 'learning_rate': 2.4854494503125676e-05, 'epoch': 1.5089458935115325, 'step': 7000}, {'loss': 0.3416627883911133, 'grad_norm': 0.44905975461006165, 'learning_rate': 2.4495221671337216e-05, 'epoch': 1.5305022634188403, 'step': 7100}, {'loss': 0.3354124450683594, 'grad_norm': 15.287354469299316, 'learning_rate': 2.4135948839548756e-05, 'epoch': 1.552058633326148, 'step': 7200}, {'loss': 0.43816486358642576, 'grad_norm': 0.3602645695209503, 'learning_rate': 2.3776676007760296e-05, 'epoch': 1.5736150032334555, 'step': 7300}, {'loss': 0.32216514587402345, 'grad_norm': 0.20203045010566711, 'learning_rate': 2.3417403175971832e-05, 'epoch': 1.595171373140763, 'step': 7400}, {'loss': 0.4019210052490234, 'grad_norm': 0.5081460475921631, 'learning_rate': 2.3058130344183372e-05, 'epoch': 1.6167277430480707, 'step': 7500}, {'loss': 0.49971359252929687, 'grad_norm': 19.39354705810547, 'learning_rate': 2.2698857512394915e-05, 'epoch': 1.6382841129553785, 'step': 7600}, {'loss': 0.3551605224609375, 'grad_norm': 0.19894228875637054, 'learning_rate': 2.2339584680606455e-05, 'epoch': 1.6598404828626858, 'step': 7700}, {'loss': 0.4340576171875, 'grad_norm': 0.5709039568901062, 'learning_rate': 2.1980311848817995e-05, 'epoch': 1.6813968527699936, 'step': 7800}, {'loss': 0.44305355072021485, 'grad_norm': 0.8321886658668518, 'learning_rate': 2.1621039017029535e-05, 'epoch': 1.702953222677301, 'step': 7900}, {'loss': 0.42251426696777344, 'grad_norm': 0.2053173929452896, 'learning_rate': 2.126176618524107e-05, 'epoch': 1.7245095925846088, 'step': 8000}, {'loss': 0.39120250701904297, 'grad_norm': 14.760652542114258, 'learning_rate': 2.090249335345261e-05, 'epoch': 1.7460659624919164, 'step': 8100}, {'loss': 0.4281676483154297, 'grad_norm': 8.370779037475586, 'learning_rate': 2.054322052166415e-05, 'epoch': 1.767622332399224, 'step': 8200}, {'loss': 0.315897102355957, 'grad_norm': 18.324146270751953, 'learning_rate': 2.0183947689875695e-05, 'epoch': 1.7891787023065315, 'step': 8300}, {'loss': 0.42815361022949217, 'grad_norm': 32.82711410522461, 'learning_rate': 1.9824674858087234e-05, 'epoch': 1.8107350722138391, 'step': 8400}, {'loss': 0.31751625061035155, 'grad_norm': 1.515242099761963, 'learning_rate': 1.9465402026298774e-05, 'epoch': 1.832291442121147, 'step': 8500}, {'loss': 0.429794921875, 'grad_norm': 19.866308212280273, 'learning_rate': 1.910612919451031e-05, 'epoch': 1.8538478120284543, 'step': 8600}, {'loss': 0.4126185989379883, 'grad_norm': 6.223877906799316, 'learning_rate': 1.874685636272185e-05, 'epoch': 1.875404181935762, 'step': 8700}, {'loss': 0.3473478698730469, 'grad_norm': 0.4292498826980591, 'learning_rate': 1.838758353093339e-05, 'epoch': 1.8969605518430697, 'step': 8800}, {'loss': 0.4773097991943359, 'grad_norm': 0.21372388303279877, 'learning_rate': 1.802831069914493e-05, 'epoch': 1.9185169217503772, 'step': 8900}, {'loss': 0.3257643508911133, 'grad_norm': 0.2776563763618469, 'learning_rate': 1.7669037867356474e-05, 'epoch': 1.9400732916576848, 'step': 9000}, {'loss': 0.4117060470581055, 'grad_norm': 0.394583135843277, 'learning_rate': 1.7309765035568014e-05, 'epoch': 1.9616296615649924, 'step': 9100}, {'loss': 0.32528297424316405, 'grad_norm': 10.801919937133789, 'learning_rate': 1.695049220377955e-05, 'epoch': 1.9831860314723002, 'step': 9200}, {'eval_loss': 0.5586886405944824, 'eval_accuracy': 0.8592672413793103, 'eval_runtime': 182.2125, 'eval_samples_per_second': 25.465, 'eval_steps_per_second': 6.366, 'epoch': 2.0, 'step': 9278}, {'loss': 0.3828012466430664, 'grad_norm': 0.3368698060512543, 'learning_rate': 1.659121937199109e-05, 'epoch': 2.0047424013796076, 'step': 9300}, {'loss': 0.2872117233276367, 'grad_norm': 0.23949964344501495, 'learning_rate': 1.623194654020263e-05, 'epoch': 2.0262987712869154, 'step': 9400}, {'loss': 0.22207590103149413, 'grad_norm': 6.572041988372803, 'learning_rate': 1.587267370841417e-05, 'epoch': 2.0478551411942227, 'step': 9500}, {'loss': 0.27318296432495115, 'grad_norm': 0.0823705866932869, 'learning_rate': 1.551340087662571e-05, 'epoch': 2.0694115111015305, 'step': 9600}, {'loss': 0.28318119049072266, 'grad_norm': 31.788537979125977, 'learning_rate': 1.5154128044837251e-05, 'epoch': 2.090967881008838, 'step': 9700}, {'loss': 0.3169443702697754, 'grad_norm': 0.2749963402748108, 'learning_rate': 1.479485521304879e-05, 'epoch': 2.1125242509161457, 'step': 9800}, {'loss': 0.3107573127746582, 'grad_norm': 0.18246571719646454, 'learning_rate': 1.443558238126033e-05, 'epoch': 2.1340806208234535, 'step': 9900}, {'loss': 0.23727466583251952, 'grad_norm': 0.16961997747421265, 'learning_rate': 1.407630954947187e-05, 'epoch': 2.155636990730761, 'step': 10000}, {'loss': 0.2684821701049805, 'grad_norm': 1.1415185928344727, 'learning_rate': 1.371703671768341e-05, 'epoch': 2.1771933606380687, 'step': 10100}, {'loss': 0.3035403060913086, 'grad_norm': 25.12548828125, 'learning_rate': 1.335776388589495e-05, 'epoch': 2.198749730545376, 'step': 10200}, {'loss': 0.26792619705200194, 'grad_norm': 0.13733625411987305, 'learning_rate': 1.299849105410649e-05, 'epoch': 2.220306100452684, 'step': 10300}, {'loss': 0.1871042823791504, 'grad_norm': 0.04888926073908806, 'learning_rate': 1.2639218222318027e-05, 'epoch': 2.241862470359991, 'step': 10400}, {'loss': 0.2644535255432129, 'grad_norm': 0.16772034764289856, 'learning_rate': 1.2279945390529569e-05, 'epoch': 2.263418840267299, 'step': 10500}, {'loss': 0.25983203887939454, 'grad_norm': 16.191234588623047, 'learning_rate': 1.1920672558741109e-05, 'epoch': 2.284975210174607, 'step': 10600}, {'loss': 0.2908240509033203, 'grad_norm': 10.298855781555176, 'learning_rate': 1.1561399726952649e-05, 'epoch': 2.306531580081914, 'step': 10700}, {'loss': 0.36338573455810547, 'grad_norm': 0.19287465512752533, 'learning_rate': 1.1202126895164189e-05, 'epoch': 2.328087949989222, 'step': 10800}, {'loss': 0.22832969665527345, 'grad_norm': 0.7376830577850342, 'learning_rate': 1.0842854063375728e-05, 'epoch': 2.3496443198965293, 'step': 10900}, {'loss': 0.23442647933959962, 'grad_norm': 0.15010835230350494, 'learning_rate': 1.0483581231587268e-05, 'epoch': 2.371200689803837, 'step': 11000}, {'loss': 0.3221405029296875, 'grad_norm': 0.07460515201091766, 'learning_rate': 1.0124308399798808e-05, 'epoch': 2.3927570597111445, 'step': 11100}, {'loss': 0.28981689453125, 'grad_norm': 0.21287886798381805, 'learning_rate': 9.765035568010346e-06, 'epoch': 2.4143134296184523, 'step': 11200}, {'loss': 0.24067361831665038, 'grad_norm': 0.04343663901090622, 'learning_rate': 9.405762736221888e-06, 'epoch': 2.4358697995257597, 'step': 11300}, {'loss': 0.2248045349121094, 'grad_norm': 0.06716863811016083, 'learning_rate': 9.046489904433428e-06, 'epoch': 2.4574261694330675, 'step': 11400}, {'loss': 0.22657609939575196, 'grad_norm': 0.3633533716201782, 'learning_rate': 8.687217072644966e-06, 'epoch': 2.4789825393403753, 'step': 11500}, {'loss': 0.2304113006591797, 'grad_norm': 0.17366865277290344, 'learning_rate': 8.327944240856508e-06, 'epoch': 2.5005389092476826, 'step': 11600}, {'loss': 0.27950578689575195, 'grad_norm': 0.2705219089984894, 'learning_rate': 7.968671409068048e-06, 'epoch': 2.5220952791549904, 'step': 11700}, {'loss': 0.1844637680053711, 'grad_norm': 1.5045969486236572, 'learning_rate': 7.609398577279586e-06, 'epoch': 2.543651649062298, 'step': 11800}, {'loss': 0.2762027359008789, 'grad_norm': 0.09152305126190186, 'learning_rate': 7.250125745491127e-06, 'epoch': 2.5652080189696056, 'step': 11900}, {'loss': 0.21781009674072266, 'grad_norm': 0.04706695303320885, 'learning_rate': 6.8908529137026665e-06, 'epoch': 2.5867643888769134, 'step': 12000}, {'loss': 0.1974589729309082, 'grad_norm': 55.45185470581055, 'learning_rate': 6.5315800819142055e-06, 'epoch': 2.6083207587842208, 'step': 12100}, {'loss': 0.4089201354980469, 'grad_norm': 0.059052277356386185, 'learning_rate': 6.172307250125746e-06, 'epoch': 2.629877128691528, 'step': 12200}, {'loss': 0.3000698471069336, 'grad_norm': 0.6451592445373535, 'learning_rate': 5.813034418337285e-06, 'epoch': 2.651433498598836, 'step': 12300}, {'loss': 0.20111818313598634, 'grad_norm': 18.982114791870117, 'learning_rate': 5.453761586548826e-06, 'epoch': 2.6729898685061437, 'step': 12400}, {'loss': 0.33607948303222657, 'grad_norm': 0.0818820670247078, 'learning_rate': 5.094488754760365e-06, 'epoch': 2.694546238413451, 'step': 12500}, {'loss': 0.18176643371582032, 'grad_norm': 0.050265878438949585, 'learning_rate': 4.735215922971905e-06, 'epoch': 2.716102608320759, 'step': 12600}, {'loss': 0.2949331092834473, 'grad_norm': 18.93984603881836, 'learning_rate': 4.375943091183445e-06, 'epoch': 2.7376589782280663, 'step': 12700}, {'loss': 0.33234348297119143, 'grad_norm': 0.21386009454727173, 'learning_rate': 4.016670259394985e-06, 'epoch': 2.759215348135374, 'step': 12800}, {'loss': 0.1973973274230957, 'grad_norm': 0.5056614279747009, 'learning_rate': 3.6573974276065243e-06, 'epoch': 2.780771718042682, 'step': 12900}, {'loss': 0.2784450531005859, 'grad_norm': 0.036860350519418716, 'learning_rate': 3.2981245958180646e-06, 'epoch': 2.802328087949989, 'step': 13000}, {'loss': 0.3263077163696289, 'grad_norm': 10.363059043884277, 'learning_rate': 2.938851764029604e-06, 'epoch': 2.8238844578572966, 'step': 13100}, {'loss': 0.32799831390380857, 'grad_norm': 0.17685957252979279, 'learning_rate': 2.5795789322411444e-06, 'epoch': 2.8454408277646044, 'step': 13200}, {'loss': 0.1836163139343261

In [35]:
trainer.save_model(
    "../models/distilbert_model"
)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [37]:
tokenizer.save_pretrained(
    "../models/distilbert_model"
)

('../models/distilbert_model\\tokenizer_config.json',
 '../models/distilbert_model\\tokenizer.json')

In [32]:
predictions = trainer.predict(test_dataset)

preds = np.argmax(
    predictions.predictions,
    axis=1
)

accuracy = accuracy_score(
    test_labels,
    preds
)

print("DistilBERT Accuracy:", accuracy)

C:\Users\HP\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

DistilBERT Accuracy: 0.8515086206896552

In [33]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

In [34]:
trainer.evaluate()

C:\Users\HP\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

RuntimeError: on_train_begin must be called before on_evaluate